apiVersion: apps/v1
kind: Deployment
metadata:
  name:  APP_NAME
  labels:
    app:  APP_NAME
spec:
  selector:
    matchLabels:
      app: APP_NAME
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  APP_NAME
    spec:
      containers:
      - name:  APP_NAME
        image:  REGISTRY/SERVICE_NAME:IMAGE_VERSION
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 256m
            memory: 256Mi
        env:
        - name: FROM_REDIS_HOST
          value: "1"
        - name: TO_REDIS_HOST
          value: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
spec:
  selector:
    app: APP_NAME
  type: ClusterIP
  ports:
  - name: APP_NAME
    port: 80
    targetPort: 80